### ISSUE TITLE
No PASS reports since June 2015

### ISSUE THREAD

**Issue by eserte** [damog/www-tumblr#12]
See http://matrix.cpantesters.org/?dist=WWW-Tumblr%205.1;reports=1#sl=7,1 for a datetime-sorted list of test reports.

On my system it fails like this:
```
Trying to post type quote without: quote at t/06-blog_postings.t line 27.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 4.
t/06-blog_postings.t ..........
Dubious, test returned 255 (wstat 65280, 0xff00)
All 4 subtests passed
```

**Comment by damog** [comment]
Fixed on 5.2. Maybe one day I will properly fix the versioning.

**Comment by eserte** [comment]
Unfortunately there are still no pass reports: http://fast-matrix.cpantesters.org/?dist=WWW-Tumblr%205.2

**Comment by damog** [comment]
But this is now due to API limiting which happens every day. Unrelated to
the original issue and much much harder (and irrelevant) to address.

On Saturday, September 19, 2015, Slaven Rezić <notifications@github.com>
wrote:

> Unfortunately there are still no pass reports:
> http://fast-matrix.cpantesters.org/?dist=WWW-Tumblr%205.2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/damog/www-tumblr/issues/12#issuecomment-141701802>.
>


-- 
http://damog.net
