### ISSUE TITLE
Not Building 

### ISSUE THREAD

**Issue by jacoby** [damog/www-tumblr#13]
Fails in the test, on two x86 Linux machines. Perl 5.18.0 and 5.24.0.

t/02-blog_avatar.t ............ 1/? malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "\x{fffd}PNG\r\n\x{1a}...") at /home/jacoby/.cpan/build/WWW-Tumblr-5.2-UxjAuQ/blib/lib/WWW/Tumblr/API.pm line 37.

**Comment by jacoby** [comment]
Addendum: Tumblr API returns the PNG of the avatar, not the URL of the avatar.

**Comment by jacoby** [comment]
Since the API is GET-only here, I see three possibilities:

1) Adapt the API and rewrite tests to handle the PNG, perhaps using Perl::Magick to ensure that asking for size 128 returns a 128x128 PNG

2) write the module so that, when handling avatars, it returns 'https://api.tumblr.com/v2/blog/{blog}.tumblr.com/avatar/{size}' instead of what $blog->({size=>{size}}) returns

3) excise avatar functionality entirely.

I can do any of these or none of these.

**Comment by damog** [comment]
Thanks for reporting. Apparently the Tumblr API started responding with the image directly only very recently. It seems like using an OAuth signature is necessary even for those methods that are not necessary to authenticate. This is very annoying, but it the tests pass for now. I will be looking into rewriting some of the core methods to make this not a shitshow. Thanks Tumblr! Not.
